### ISSUE TITLE
postmessage data invalid json:  SyntaxError: Unexpected token F(…)

### ISSUE THREAD

**Issue by mauritzswanepoel** [travist/seamless.js#10]
I am getting a console log with the following message upon loading the iframe sent from seamless.parent.min.js:2

postmessage data invalid json:  SyntaxError: Unexpected token F(…)

**Comment by travist** [comment]
Cannot reproduce. Please try latest version.

**Comment by thelimarenan** [comment]
I guess that error is also occurs in the browser console when you accesses the page of the library

http://travistidwell.com/seamless.js/
