### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contentWindow' of undefined

### ISSUE THREAD

**Issue by laradevitt** [travist/seamless.js#12]
It's been a loong time since I've dealt with iframes, so this may be a silly question.

I'm testing using seamless.js within a Drupal installation. My "parent" page contains the following:

```
<head>
<script type="text/javascript" src="https://cdn.rawgit.com/travist/seamless.js/master/build/seamless.parent.js"></script>

<script type="text/javascript">
<!--//--><![CDATA[//><!--

  (function($) {
    $("#myiframe").seamless({ 
      container: "body"
    });
  }(jQuery));

//--><!]]>
</script>
</head>

<iframe id="myiframe" src="/d7_dev1/sites/all/modules/seamless/templates/index.html" style="width:100%;border:none;"></iframe>
```

The "child" page (index.html) includes the appropriate JS file:

```
<head>
  <script type="text/javascript" src="https://cdn.rawgit.com/travist/seamless.js/master/build/seamless.child.js"></script>
</head>
```

The child page is loading up in the iframe, but I am receiving the following error:

( Chrome 53.0.2)

<pre>
seamless.parent.js:847 Uncaught TypeError: Cannot read property 'contentWindow' of undefined
</pre>

(Firefox 48.0.1)

<pre>
seamless.parent.js:847:5 TypeError: iframe[0] is undefined
</pre>

Adding a timeout() to the inline JS resolves the error, but then I get the "Loading..." prompt followed by _An error has been detected on this page. Click here to open in a separate window_. This is what I would expect if my child page were on another domain, which it isn't.

I'm at a bit of a loss so would appreciate any pointers. Thanks in advance!

**Comment by travist** [comment]
This is because you are checking for the iframe before it is a part of the DOM. I recommend wrapping the seamless call in a ```window.onload``` to ensure the DOM is loaded before calling into seamless.
