### ISSUE TITLE
What is $.pm?

### ISSUE THREAD

**Issue by manoj-cybage** [travist/seamless.js#14]
// Make sure we have the $.pm module loaded.
  if (!$.hasOwnProperty('pm')) {
    console.log('You must install the jQuery.pm module to use seamless.js.');
    return;
  }

What is $.pm module? from where we can download it?

**Comment by lukaskolafa** [comment]
I assume it is probably postmessage module? https://github.com/daepark/postmessage/tree/881a6cd11f333c3bb3017e403f14107ac0b5baa0

**Comment by travist** [comment]
I just updated this library to no longer require jQuery, so you can now use it as...

```
window.pm()
```

You still need this library though.
